# Generated by Django 6.0.6 on 2026-06-21 20:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('token_balance', models.IntegerField(default=10)),
                ('profile_ready', models.BooleanField(default=False)),
                ('skills', models.TextField(blank=True, help_text='List your skills')),
                ('experience', models.TextField(blank=True, help_text='Previous work experience')),
                ('roles', models.TextField(blank=True, help_text='Roles you have held')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('interests', models.TextField(blank=True)),
                ('fun_fact', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('availability_times', models.TextField(blank=True, help_text='Usual availability times')),
                ('linkedin_link', models.URLField(blank=True)),
                ('offerings', models.TextField(blank=True, help_text='Optional: things you can provide or share with others')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('executive', 'Executive')], max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('study_field', models.CharField(blank=True, help_text='e.g. Computer Science', max_length=255)),
                ('university', models.CharField(blank=True, help_text='University name', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('why_choose_mentor', models.TextField()),
                ('session_objectives', models.TextField()),
                ('calendly_link', models.URLField(blank=True, help_text="Mentee's Calendly event link", max_length=500, null=True)),
                ('token_escrowed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_meetings', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_rating', models.IntegerField(default=0)),
                ('experience_rating', models.IntegerField(default=0)),
                ('roles_rating', models.IntegerField(default=0)),
                ('cv_rating', models.IntegerField(default=0)),
                ('interest_rating', models.IntegerField(default=0)),
                ('fun_fact_rating', models.IntegerField(default=0)),
                ('summary_rating', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.meeting')),
            ],
            options={
                'unique_together': {('meeting', 'evaluator')},
            },
        ),
    ]
